[[redirects]]
  from = "/product"
  to = "/index.html"  
  status = 200

[[redirects]]
  from = "/quiz"
  to = "/index.html"  
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"  
  status = 200

